# Generated by Django 5.2 on 2025-04-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('select', 'Select'), ('black', 'Black'), ('white', 'White')], default='select', max_length=255)),
                ('size', models.CharField(choices=[('select', 'Select'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='select', max_length=255)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('select', 'Select'), ('cloth', 'Cloth'), ('accessories', 'Accessories')], default='select', max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
